/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/scenewcreature.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scenewcreature.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[1.104, 1.577, -1.993]} rotation={[Math.PI / 2, 0, 0]} scale={0.399} />
        <group name="Empty001" position={[-0.376, 1.509, -1.183]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.124} />
        <group name="Empty002" position={[-0.294, 1.577, -1.223]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.399} />
        <group name="Empty003" position={[0.645, 1.457, -2.296]} rotation={[Math.PI / 2, 0, 0]} scale={0.23} />
        <group name="Walls" position={[0, 2, 0]}>
          <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials.Walls} />
          <mesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials.Floor} />
        </group>
        <mesh name="Floor_Frame" geometry={nodes.Floor_Frame.geometry} material={materials['Wall Moulding']} position={[0, 2.027, 0]} />
        <group name="Rug" position={[0.744, 0.264, 0.575]} rotation={[0, -1.571, 0]}>
          <mesh name="Cube040" geometry={nodes.Cube040.geometry} material={materials.Rug} />
          <mesh name="Cube040_1" geometry={nodes.Cube040_1.geometry} material={materials['Rug Sides']} />
        </group>
        <group name="Floor" position={[0.113, 0.24, 0.151]} scale={1.005}>
          <mesh name="Cube039" geometry={nodes.Cube039.geometry} material={materials.Floor} />
          <mesh name="Cube039_1" geometry={nodes.Cube039_1.geometry} material={materials['Floor 2']} />
        </group>
        <mesh name="Table_Top" geometry={nodes.Table_Top.geometry} material={materials.Material} position={[0.957, 1.199, -1.192]}>
          <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials.White} position={[0.615, -0.116, 0.539]} rotation={[Math.PI / 2, 0, 0]} scale={[0.972, 0.939, 1]} />
          <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials.White} position={[0.615, -0.353, 0.539]} rotation={[Math.PI / 2, 0, 0]} scale={[0.972, 0.939, 1]} />
          <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials.White} position={[0.615, -0.596, 0.539]} rotation={[Math.PI / 2, 0, 0]} scale={[0.972, 0.939, 1]} />
          <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={materials.White} position={[0.615, -0.836, 0.539]} rotation={[Math.PI / 2, 0, 0]} scale={[0.972, 0.939, 1]} />
          <mesh name="Drawers" geometry={nodes.Drawers.geometry} material={materials.Material} position={[0.61, 0.004, 0.027]} scale={[0.989, 1, 0.939]} />
          <mesh name="Table_Top002" geometry={nodes.Table_Top002.geometry} material={materials.Material} position={[-0.897, 0, 0.461]} />
        </mesh>
        <mesh name="Table_Top001" geometry={nodes.Table_Top001.geometry} material={materials.Floor} position={[-1.202, 1.943, -1.603]} />
        <mesh name="Table_Top003" geometry={nodes.Table_Top003.geometry} material={materials.Floor} position={[-0.531, 1.657, -1.603]} />
        <mesh name="Table_Top006" geometry={nodes.Table_Top006.geometry} material={materials.Floor} position={[-1.56, 2.468, 1.194]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Sheets" geometry={nodes.Sheets.geometry} material={materials.Sheets} position={[-0.887, 0.874, -0.188]}>
          <mesh name="Bed_Frame" geometry={nodes.Bed_Frame.geometry} material={materials.Material} position={[0.759, -0.074, 0.926]} />
          <mesh name="Mattress" geometry={nodes.Mattress.geometry} material={materials.Mattress} position={[0, 0.061, -0.251]} />
          <mesh name="Pillow" geometry={nodes.Pillow.geometry} material={materials.Sheets} position={[0.014, 0.179, -1.178]} rotation={[0.338, 0.011, 0.028]} />
          <mesh name="Small_Pillow" geometry={nodes.Small_Pillow.geometry} material={materials.Tan} position={[-0.256, 0.226, -0.799]} rotation={[0.514, 0.466, -0.164]} />
        </mesh>
        <mesh name="Window_Frame" geometry={nodes.Window_Frame.geometry} material={materials.Floor} position={[0.96, 2.534, -1.887]} />
        <group name="Upper_Window" position={[0.96, 2.534, -2.095]}>
          <mesh name="Cube012_1" geometry={nodes.Cube012_1.geometry} material={materials.White} />
          <mesh name="Cube012_2" geometry={nodes.Cube012_2.geometry} material={materials['Window Light']} />
        </group>
        <group name="Lower_Window" position={[0.96, 1.634, -2.031]}>
          <mesh name="Cube013_1" geometry={nodes.Cube013_1.geometry} material={materials.White} />
          <mesh name="Cube013_2" geometry={nodes.Cube013_2.geometry} material={materials['Window Light']} />
        </group>
        <mesh name="Blinds" geometry={nodes.Blinds.geometry} material={materials.Shade} position={[0.96, 2.534, -1.783]} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials.White} position={[0.96, 2.278, -1.783]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials.White} position={[0.96, 3.408, -1.783]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh name="Seat" geometry={nodes.Seat.geometry} material={materials.Yellow} position={[0.549, 1.05, -0.404]} rotation={[0, -0.33, 0]}>
          <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Material.003']} position={[0, -0.602, -0.135]} />
          <mesh name="Cylinder006" geometry={nodes.Cylinder006.geometry} material={materials['Material.004']} position={[-0.001, -0.41, -0.136]} />
          <mesh name="Cylinder007" geometry={nodes.Cylinder007.geometry} material={materials['Material.005']} position={[0.331, -0.738, -0.135]} rotation={[Math.PI / 2, 0, 2.267]} />
          <mesh name="Cylinder008" geometry={nodes.Cylinder008.geometry} material={materials['Material.005']} position={[0.166, -0.738, 0.155]} rotation={[Math.PI / 2, 0, 1.919]} />
          <mesh name="Cylinder009" geometry={nodes.Cylinder009.geometry} material={materials['Material.005']} position={[-0.167, -0.738, 0.155]} rotation={[Math.PI / 2, 0, 2.042]} />
          <mesh name="Cylinder010" geometry={nodes.Cylinder010.geometry} material={materials['Material.005']} position={[-0.334, -0.738, -0.135]} rotation={[Math.PI / 2, 0, 1.896]} />
          <mesh name="Cylinder011" geometry={nodes.Cylinder011.geometry} material={materials['Material.005']} position={[-0.167, -0.738, -0.423]} rotation={[Math.PI / 2, 0, 2.545]} />
          <mesh name="Cylinder012" geometry={nodes.Cylinder012.geometry} material={materials['Material.005']} position={[0.166, -0.738, -0.425]} rotation={[Math.PI / 2, 0, 1.898]} />
        </mesh>
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Dark Gray']} position={[0.206, 1.279, -1.351]} rotation={[0, 1.254, 0]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.Tan} position={[0.2, 1.329, -1.362]} rotation={[0, 0.156, 0]} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.Blue} position={[0.2, 1.358, -1.362]} rotation={[0, 0.03, 0]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Dark Gray']} position={[-0.528, 1.856, -1.63]} rotation={[-Math.PI, 0, -1.748]} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.Tan} position={[-0.613, 1.868, -1.608]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Material.008']} position={[-0.688, 1.842, -1.6]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['Leathery brown']} position={[-0.386, 1.732, -1.531]} rotation={[Math.PI, -0.156, Math.PI]} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials['Dark Gray']} position={[-1.61, 2.684, 1.596]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials['Leathery brown']} position={[-1.61, 2.694, 1.52]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Dark Gray']} position={[-1.61, 2.689, 1.44]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials.Tan} position={[-1.501, 2.526, 1.183]} rotation={[-Math.PI, 0.067, -Math.PI]} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials.Blue} position={[-1.501, 2.573, 1.183]} rotation={[-Math.PI, 0.025, -Math.PI]} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials.Yellow} position={[-1.501, 2.612, 1.183]} rotation={[-Math.PI, 0.25, -Math.PI]} />
        <mesh name="Circle004" geometry={nodes.Circle004.geometry} material={materials.Pot} position={[0.387, 1.685, -1.771]}>
          <mesh name="Sphere004" geometry={nodes.Sphere004.geometry} material={materials.Cactus} position={[0, 0.047, 0]} scale={[0.435, 0.344, 0.435]} />
          <mesh name="Sphere005" geometry={nodes.Sphere005.geometry} material={materials.Cactus} position={[0.056, 0.051, 0]} rotation={[0, 0, -0.797]} scale={[0.182, 0.141, 0.209]} />
        </mesh>
        <mesh name="Circle005" geometry={nodes.Circle005.geometry} material={materials.Pot} position={[-1.581, 2.574, 0.804]} rotation={[0, -1.555, 0]}>
          <mesh name="Sphere006" geometry={nodes.Sphere006.geometry} material={materials.Cactus} position={[0, 0.059, 0]} scale={[0.542, 0.428, 0.542]} />
          <mesh name="Sphere007" geometry={nodes.Sphere007.geometry} material={materials.Cactus} position={[0.069, 0.064, 0]} rotation={[0, 0, -0.797]} scale={[0.226, 0.176, 0.26]} />
          <mesh name="Sphere008" geometry={nodes.Sphere008.geometry} material={materials.Cactus} position={[-0.073, 0.111, -0.008]} rotation={[Math.PI, 0.108, 2.484]} scale={[0.299, 0.232, 0.343]} />
        </mesh>
        <mesh name="Circle006" geometry={nodes.Circle006.geometry} material={materials.Pot} position={[-1.292, 0.465, 1.632]} rotation={[0, -1.555, 0]} scale={1.418}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.002']} position={[0.003, 0.052, -0.183]} rotation={[0, 1.555, -0.367]} scale={0.778} />
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.002']} position={[0.152, 0.119, -0.034]} rotation={[-0.023, 0.238, -0.204]} scale={0.75} />
          <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.002']} position={[-0.163, 0.134, -0.124]} rotation={[3.115, 0.68, 2.669]} scale={0.899} />
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.002']} position={[-0.082, 0.091, 0.137]} rotation={[-3.064, -1.013, 2.908]} scale={0.928} />
          <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['Material.002']} position={[0.126, 0.065, 0.135]} rotation={[0, -1.128, -0.367]} scale={0.62} />
          <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['Material.002']} position={[0.011, 0.221, -0.136]} rotation={[-0.803, 1.539, 0.593]} scale={0.612} />
          <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials['Material.002']} position={[-0.117, 0.233, 0.048]} rotation={[3.078, -0.671, 2.845]} scale={0.797} />
          <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials['Material.002']} position={[0.111, 0.207, 0.033]} rotation={[-0.042, -0.232, -0.309]} scale={0.696} />
          <mesh name="Plane011_3" geometry={nodes.Plane011_3.geometry} material={materials['Material.002']} position={[0.072, 0.291, -0.071]} rotation={[-0.029, 0.681, -0.191]} scale={[0.548, 0.701, 0.54]} />
          <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials['Material.002']} position={[-0.116, 0.291, -0.049]} rotation={[3.091, 0.195, 2.894]} scale={[0.719, 0.908, 0.703]} />
          <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials['Material.002']} position={[0.015, 0.27, 0.093]} rotation={[-2.792, -1.451, -3.094]} scale={[0.672, 0.839, 0.653]} />
        </mesh>
        <group name="Cylinder019" position={[-0.191, 1.789, -1.596]}>
          <mesh name="Cylinder019_1" geometry={nodes.Cylinder019_1.geometry} material={materials.Candle} />
          <mesh name="Cylinder019_2" geometry={nodes.Cylinder019_2.geometry} material={materials['Candle Wick']} />
        </group>
        <group name="Entertainment_System" position={[1.54, 1.246, -1.084]} rotation={[0, -0.386, 0]}>
          <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials['Creamy Yellow']} />
          <mesh name="Plane011_1" geometry={nodes.Plane011_1.geometry} material={materials['Creamy Yellow']} />
          <mesh name="Plane011_2" geometry={nodes.Plane011_2.geometry} material={materials['Creamy Yellow']} />
          <mesh name="Circle007" geometry={nodes.Circle007.geometry} material={materials.Button} position={[-0.112, 0.048, 0.345]} rotation={[0, -0.215, 0.004]} />
          <mesh name="Circle008" geometry={nodes.Circle008.geometry} material={materials.Button} position={[-0.082, 0.048, 0.351]} rotation={[0, -0.215, 0.004]} />
          <mesh name="Circle009" geometry={nodes.Circle009.geometry} material={materials.Black} position={[0.1, 0.038, 0.123]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh name="Circle012" geometry={nodes.Circle012.geometry} material={materials.Button} position={[0.03, 0.206, 0.156]} rotation={[1.648, -0.201, 0.37]} />
          <mesh name="Circle013" geometry={nodes.Circle013.geometry} material={materials.Button} position={[0.059, 0.206, 0.167]} rotation={[1.648, -0.201, 0.37]} />
          <mesh name="Circle014" geometry={nodes.Circle014.geometry} material={materials.Button} position={[-0.156, 0.04, 0.14]} rotation={[1.82, -0.215, 0]} />
          <mesh name="Circle015" geometry={nodes.Circle015.geometry} material={materials.Button} position={[-0.124, 0.04, 0.14]} rotation={[1.82, -0.215, 0]} />
          <mesh name="Cube015_1" geometry={nodes.Cube015_1.geometry} material={materials['Dark Gray']} position={[-0.185, 0.047, 0.328]} rotation={[0, -0.215, 0.004]} />
          <group name="Plane008">
            <mesh name="Plane021_1" geometry={nodes.Plane021_1.geometry} material={materials.Gray} />
            <mesh name="Plane021_2" geometry={nodes.Plane021_2.geometry} material={materials.Gray} />
          </group>
          <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={materials.Gray} />
          <group name="Plane017">
            <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials['Creamy Yellow']} />
            <mesh name="Plane009_1" geometry={nodes.Plane009_1.geometry} material={materials['Creamy Yellow']} />
          </group>
          <mesh name="Plane019" geometry={nodes.Plane019.geometry} material={materials['Dark Gray']} position={[-0.001, 0.176, -0.001]} rotation={[0, -0.358, 0]} />
          <mesh name="Plane020" geometry={nodes.Plane020.geometry} material={materials['Material.010']} position={[-0.045, 0.35, 0.117]} rotation={[0, -0.358, 0]} />
          <mesh name="Plane021" geometry={nodes.Plane021.geometry} material={materials['Creamy Yellow']} position={[-0.139, 0.004, 0.34]} rotation={[0, -0.215, 0.004]} />
          <mesh name="Vert" geometry={nodes.Vert.geometry} material={materials.Black} position={[0.1, 0.038, 0.139]} />
        </group>
        <group name="Walls001" position={[-1.776, 2.562, -0.62]} scale={1.277}>
          <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials.White} />
          <mesh name="Cube024_1" geometry={nodes.Cube024_1.geometry} material={materials.Poster} />
        </group>
        <group name="Table_Top004" position={[-0.455, 2.794, -1.755]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials['Material.006']} />
          <mesh name="Cube022_1" geometry={nodes.Cube022_1.geometry} material={materials['CW Painting']} />
        </group>
        <group name="Table_Top005" position={[-1.322, 2.541, -1.747]} rotation={[Math.PI / 2, 0, Math.PI]}>
          <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials.Canvas} />
          <mesh name="Cube023_1" geometry={nodes.Cube023_1.geometry} material={materials['TC Painting']} />
        </group>
        <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials['Material.001']} position={[-0.764, 0.253, 1.314]} rotation={[0, -0.66, 0]}>
          <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials['Material.001']} position={[0, 1.511, 0.26]} rotation={[-0.988, 0, 0]} />
          <mesh name="Cylinder013" geometry={nodes.Cylinder013.geometry} material={materials['Material.001']} position={[0.001, 1.689, -0.001]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials['Material.001']} position={[0.001, 2.392, -1.05]} rotation={[0.249, 0.144, -0.699]} />
        </mesh>
        <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials['Material.001']} position={[1.713, 1.248, -1.518]} rotation={[Math.PI, -0.09, Math.PI]}>
          <mesh name="Cylinder014" geometry={nodes.Cylinder014.geometry} material={materials.Metal} position={[-0.081, 0.204, 0]} rotation={[-Math.PI, 0, 2.644]} />
          <mesh name="Cylinder015" geometry={nodes.Cylinder015.geometry} material={materials['Material.001']} position={[-0.15, 0.328, 0.003]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
          <mesh name="Cylinder016" geometry={nodes.Cylinder016.geometry} material={materials.Metal} position={[-0.048, 0.423, 0.003]} rotation={[Math.PI, 0, -2.32]} />
          <mesh name="Cylinder017" geometry={nodes.Cylinder017.geometry} material={materials['Material.001']} position={[0.066, 0.527, 0.003]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
          <mesh name="Cylinder018" geometry={nodes.Cylinder018.geometry} material={materials.Metal} position={[0.112, 0.535, 0.003]} rotation={[-Math.PI, 0, -1.737]} />
          <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Material.001']} position={[0, 0.058, 0]} />
          <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials['Material.001']} position={[0.26, 0.484, 0.003]} rotation={[0, 0, 0.358]} />
          <mesh name="Sphere003" geometry={nodes.Sphere003.geometry} material={materials['Material.001']} position={[0.161, 0.541, 0.003]} rotation={[0, 0, 1.056]} />
        </mesh>
        <mesh name="Top_Housing" geometry={nodes.Top_Housing.geometry} material={materials['Material.009']} position={[0.515, 1.293, -0.831]} rotation={[0, 0.052, 0]}>
          <mesh name="клавиатура001" geometry={nodes.клавиатура001.geometry} material={materials['Material.011']} position={[0.04, 0.003, 0.053]} rotation={[1.628, 0, -2.527]} />
        </mesh>
        <group name="Apple_M0100_Mouse_-_Upper_Shell" position={[0.88, 1.246, -0.911]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Apple_M0100_Mouse_-_Upper_Shell_1" geometry={nodes['Apple_M0100_Mouse_-_Upper_Shell_1'].geometry} material={materials['Material.009']} />
          <mesh name="Apple_M0100_Mouse_-_Upper_Shell_2" geometry={nodes['Apple_M0100_Mouse_-_Upper_Shell_2'].geometry} material={materials['Material.007']} />
        </group>
        <mesh name="Computer001" geometry={nodes.Computer001.geometry} material={materials['Material.011']} position={[0.629, 1.265, -1.136]} />
        <mesh name="Computer" geometry={nodes.Computer.geometry} material={materials['Material.009']} position={[0.581, 1.265, -1.136]} />
        <group name="Creature" position={[-0.921, 2.162, -1.598]} rotation={[0, -1.264, 0]}>
          <mesh name="Cube509_Cube002" geometry={nodes.Cube509_Cube002.geometry} material={materials['Material.023']} />
          <mesh name="Cube509_Cube002_1" geometry={nodes.Cube509_Cube002_1.geometry} material={materials['Material.033']} />
          <mesh name="Cube509_Cube002_2" geometry={nodes.Cube509_Cube002_2.geometry} material={materials['Material.034']} />
          <mesh name="Cube509_Cube002_3" geometry={nodes.Cube509_Cube002_3.geometry} material={materials['Material.035']} />
          <mesh name="Creature_Ear" geometry={nodes.Creature_Ear.geometry} material={materials['Material.023']} position={[1.796, -2.099, -0.328]} rotation={[-3.09, 1.531, 3.084]} />
          <mesh name="Creature002" geometry={nodes.Creature002.geometry} material={materials['Material.033']} position={[1.803, -2.218, -0.449]} />
        </group>
        <group name="Plane010" position={[-0.527, 0.959, 0.478]} rotation={[0, 0.873, 0.035]}>
          <mesh name="Plane024" geometry={nodes.Plane024.geometry} material={materials['Magazine Cover']} />
          <mesh name="Plane024_1" geometry={nodes.Plane024_1.geometry} material={materials.Magazine} />
          <group name="Empty004" rotation={[Math.PI / 2, 0, 0]} scale={0.175} />
        </group>
        <mesh name="Plane014" geometry={nodes.Plane014.geometry} material={nodes.Plane014.material} position={[-0.527, 0.959, 0.478]} rotation={[0, 0.869, 0.026]} />
        <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={nodes.Plane018.material} position={[-0.527, 0.959, 0.478]} rotation={[0, 0.869, 0.017]} />
        <mesh name="Plane022" geometry={nodes.Plane022.geometry} material={nodes.Plane022.material} position={[-0.527, 0.959, 0.478]} rotation={[0, 0.869, 0.009]} />
        <mesh name="Plane023" geometry={nodes.Plane023.geometry} material={nodes.Plane023.material} position={[-0.527, 0.959, 0.478]} rotation={[0, 0.873, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scenewcreature.glb')
